# Site settings
title: Your awesome title
author: Your Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media profiles
twitter: "https://twitter.com/project"
github: "https://github.com/user/project"
slack: "https://project.slack.com"
stackoverflow: "https://stackoverflow.com/questions/tagged/project"

# Build settings
markdown: kramdown
# theme: Docyll
sass:
  sass_dir: assets/css
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/